import { LastCont } from "@/components/LastCont";
import { MiddleCont } from "@/components/MiddleCont";
import { SongCont } from "@/components/SongCont";
import { TopContainer } from "@/components/TopContainer";
import { Box } from "@mui/material";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Next Shyna</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopContainer />
      <SongCont />
      <MiddleCont />
      <LastCont />
    </>
  );
}
